title: APIToS : Towards a Creative Commons model for API Terms of Service 
logo:
description: "Digital Infrastructure Research 2020 laureate (The Ford Foundation) "
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
